[tox]
env_list =
    test,
    bandit,
    lint
skipdist = True
skip_missing_interpreters = True
minversion = 4.47.2

[testenv]
package = skip
skip_install = true
allowlist_externals = uv

[testenv:test]
description = run the tests with pytest
commands =
    uv run --active pytest -p no:warnings -p no:logging

[testenv:bandit]
description = run security checks with bandit
commands =
    uv run --active bandit main.py

[testenv:lint]
description = lint code with ruff
commands =
    uv run --active ruff check main.py --ignore E402

