[tox]
env_list =
    py313, bandit, lint, test
skipdist =
    True
skip_missing_interpreters =
    True
minversion = 4.47.2

[testenv:test]
description = run the tests with pytest
skip_install = true
allowlist_externals = uv
commands =
    uv run --active pytest -p no:warnings -p no:logging

[testenv:bandit]
description = run security checks with bandit
skip_install = true
allowlist_externals = uv
commands =
    uv run --active bandit main.py

[testenv:lint]
description = lint code with ruff
skip_install = true
allowlist_externals = uv
commands =
    uv run --active ruff check main.py --ignore E402

